/*https://codepen.io/allistairlee/pen/pVZKxv*/
$(function(){
	$(".typewriter").typed({
		strings: ["<u style=\"color: #75ff75;\"<b style=\"color: #98FB98; font-size: 30px; \">1</b></u><br/>Не взрывайся, пожалуйста.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">2</b></u><br/><br/>Вот когда у тебя ничего нет блять.... а вот когда у тебя всё есть, тогда...",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">3</b></u><br/><br/>Какая говядина мне звонит?",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">4</b></u><br/><br/>Я не слушал [серёгу пирата], но говорят что прикольно.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">5</b></u><br/><br/>Я когда понял это слово, я такой... блять, настолько всё плохо?",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">6</b></u><br/><br/>Ты понимаешь что она только на словах пиздит? А на словах она только пиздит, а на деле...",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">7</b></u><br/><br/>— Документ?<br/>— Нахуй ментов!",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">8</b></u><br/><br/>Если вы подумаете выпускать книгу с моими цитатами и не поделитесь деньгами... пизда вам, свиньи ебаные.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">9</b></u><br/><br/>Менты не стоят нихуя.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">10</b></u><br/><br/>От таких великих инвестиций у меня шишка встала, счас стены ебать начну.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">11</b></u><br/><br/>У меня в голове пиздец блять.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">12</b></u><br/><br/>У меня нет имени, а фамилия не распространяется.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">13</b></u><br/><br/>Я приду, я отключу игру нахуй, даже не включу её.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">14</b></u><br/><br/>В этом есть что-то похожее на правду.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">15</b></u><br/><br/>Называется хентай с пивом.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">16</b></u><br/><br/>Вы заебанцы хуевские.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">17</b></u><br/><br/>За любое убийство садят так-то.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">18</b></u><br/><br/>Когда твоя мать на горе свистнет.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">19</b></u><br/><br/>Пакет по-английски будет багет.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">20</b></u><br/><br/>Всё равно я, блять... похуй.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">21</b></u><br/><br/>Под это [серёга пират] ахуенно срать.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">22</b></u><br/><br/>Выебать в пизду до талого.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">23</b></u><br/><br/>Проще жалко этого человека, чем не жалко этого человека.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">24</b></u><br/><br/>Столица России..? Это же не Москва?",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">25</b></u><br/><br/>Хуебятина.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">26</b></u><br/><br/>Я даже не травился, я хавал.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: ради будущих детей.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">27</b></u><br/><br/>Все люди когда-то уподохнут.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">28</b></u><br/><br/>Медики делают неправильные дела.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">29</b></u><br/><br/>Палёнщина.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">30</b></u><br/><br/>Немцы, русские... Похуй — хачи.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">31</b></u><br/><br/>Если бы ты пил вино, я бы тебя сдезь уже не было. Я бы тебя захуярил. Вино — это элитное.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">32</b></u><br/><br/>Сельское говно.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">33</b></u><br/><br/>По фене побазарить.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">34</b></u><br/><br/>Я прошёл, не было то время.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">35</b></u><br/><br/>Буду я ещё себе обрезать жизнь, на полпути...",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">36</b></u><br/><br/>Лысый два по пять.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: автор цитаты после 26-го апреля.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">37</b></u><br/><br/>Свиноотдел блять.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">38</b></u><br/><br/>Объебос русского народа.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">39</b></u><br/><br/>Девки пиздят, пацаны делают.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">40</b></u><br/><br/>Как говорится: скучно жить, можно и хуйню сказать.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">41</b></u><br/><br/>Если есть космос, то должна быть и Земля.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">42</b></u><br/><br/>Один раз в жизни живём — можно переспать.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: кому угодно, но не тебе.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">43</b></u><br/><br/>Пахнет гнилым. Этот вкус... запах помойки.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">44</b></u><br/><br/>Лучше потерять, чем обрести.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">45</b></u><br/><br/>Вообще-то на самом деле... середина всегда в конце.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">46</b></u><br/><br/>О! Вышел. То есть пришёл... Дядя блять. Петя.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">47</b></u><br/><br/>Ты хочешь, чтобы я встал и тебе этот тапок в горло засунул?",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">48</b></u><br/><br/>...А ты не плачь.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">49</b></u><br/><br/>Крабы... одним словом дота.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">50</b></u><br/><br/>У тебя счас ебало слетит, как эти колёса.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">51</b></u><br/><br/>Ты нормальный? Бля, чё со мной произошло..?",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">52</b></u><br/><br/>Типа жижа, типа нет.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: без контекста сложно понять о чём сдезь речь. он говорил о снеге. да. он гений.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">53</b></u><br/><br/>Как говорится: без работы и денег нет.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: однако же у тебя и с работой денег нет. впрочем как и у меня.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">54</b></u><br/><br/>Я сказал, я не буду в пустоту говорить.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">55</b></u><br/><br/>Адекватный скажет, что я не несу хуйню. А если он послушает вас...",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">56</b></u><br/><br/>Вы затираете какую-то, вот вы там сверхразумы.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">57</b></u><br/><br/>Нет смысла показывать, надо слушать.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: тут согласен. вживую с этих мыслей разъёбывало гораздо сильнее.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">58</b></u><br/><br/>50. Ещё 50 и будет 100.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: я на седьмом этаже...)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">59</b></u><br/><br/>Это называется исповедь зелёного цвета.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: да, приложение так и называется. легенда, спасибо за идею.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">60</b></u><br/><br/>Воздуха больше чем пизда.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">61</b></u><br/><br/>Жирный? Нехуй жрать.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">62</b></u><br/><br/>Забудь про дорогу к моим деньгам.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">63</b></u><br/><br/>Пока [секса с ребёнком] ещё не было.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">64</b></u><br/><br/>Если он как, его надо вырезать.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">65</b></u><br/><br/>Дверь есть в рай. Пару часов в аду, пару часов в раю.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">66</b></u><br/><br/>Я не общаюсь. Только за деньги.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">67</b></u><br/><br/>Под Путина возьмёт. Ну это... колоть.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">68</b></u><br/><br/>— Я думал ты в пакет нассал.<br/>— Хотелось бы.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: за то в штаны нагадил бл...)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">69</b></u><br/><br/>— Пиратка или Элька?<br/>— Пиратка, потому что CS:GO...",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">70</b></u><br/><br/>[Притянуть] за шкибот.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">71</b></u><br/><br/>База не меняется, база остаётся неизменной.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">72</b></u><br/><br/>Всё было как в детстве.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">73</b></u><br/><br/>База — это Baz Corporated.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(контекст. прим.: фамилия одного из одногруппников была Базаров. он чухал газ, ввиду чего наша конфа называлась ПАО Bazprom.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">74</b></u><br/><br/>Нахуй вьетнамцам моя жопа?",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">75</b></u><br/><br/>Сидеть будет когда кого-то ёбнет. Далеко и надолго. Его там выебут и звёзды на жопе будут. Ауешные типа.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: почему он говорил о себе в третьем лице...)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">76</b></u><br/><br/>О чьих правах вы говорите? Имена? Явки? Фамилии? Хачи бля.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">77</b></u><br/><br/>Вот он [Нейромонах Феофан] гений и смешной, а я...",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">78</b></u><br/><br/>Не вытаскивай свою чёрную хуйню.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: оставлю без контекста, потому что понятнее не станет, а хаха эффект кончится.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">79</b></u><br/><br/>Если бы ты был таксистом, у тебя бы денег на пиво всегда хватало.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">80</b></u><br/><br/>Бля Жаль 600 руб сейчас нет А так купил бы мартини<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: сохранена орфография. это единственная цитата, которую он не сказал, а написал.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">81</b></u><br/><br/>Тот самый батя, тот самый Неверов.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">82</b></u><br/><br/>На улице пей ваще, и иди...",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">83</b></u><br/><br/>Короче надо уже думать где повеситься на шнурках.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">84</b></u><br/><br/>Чё блять? Вы блять.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">85</b></u><br/><br/>Давно я чё-то в GTA V не заходил. У меня пиздец машину спиздили.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">86</b></u><br/><br/>Что в этом такого? Обычное слово.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">87</b></u><br/><br/>Теперь каждое слово это блять... кадр ёбаный.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">88</b></u><br/><br/>Когда курс кончится, вы блять так давно меня не увидите.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: а толстяк-то походу искренне так считал.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">89</b></u><br/><br/>У меня ещё конечно мозг остался чуть-чуть, наверное, но не настолько чтобы там ещё что-то было.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: это моя любимая.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">90</b></u><br/><br/>Я говорю когда мне нужно.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">91</b></u><br/><br/>Кто такой Буш? Я блять не знаю. Он мне как мойщик окон.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: зная тебя, он тебе скорее внебрачный отец.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">92</b></u><br/><br/>Меня вроде не колбасит, не плывёт, но я вижу всё.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: пакет виноградного дня.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">93</b></u><br/><br/>Мне кажется будто тяжело идти. И как будто сложно.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: пакет виноградного дня.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">94</b></u><br/><br/>Я уже не буду сказать.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">95</b></u><br/><br/>Мои слова не все... правдивы.<br/><br/>(прим. редактора: я знаю. пиздобольшъ.)",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">96</b></u><br/><br/>Обычные фразы... но не фразы.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">97</b></u><br/><br/>У меня дома алкоголя два.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">98</b></u><br/><br/>Заткнитесь оба, а то пойдёте... один на рагу, другой на тушонку.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">99</b></u><br/><br/>У меня потребность в носках нету. У меня есть... ещё и не мало.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: добби).)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">100</b></u><br/><br/>А то оглянёшься, посмотришь, а у тебя хата горит. Ты идёшь... будешь на улице блять бомжевать.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">102</b></u><br/><br/>Я не рожаю. Меня родили. Потому что я чё, девка что ли? Если бы я был девкой — я бы вскрылся.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">103</b></u><br/><br/>Вообще зачастую... когда как.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">104</b></u><br/><br/>Если бы мой батя был отчимом, он бы мне объяснил.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">105</b></u><br/><br/>Я утром просыпаюсь, загадку услышал. Аж жить захотелось.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">106</b></u><br/><br/>Онанизм убивает.<br/><br/>(прим. редактора: а чел со знанием дела по ходу.)",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">107</b></u><br/><br/>Мне кажется, если твоя подруга со мной общаться будет, она вообще забудет кто я нахуй.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: не, такое уже никогда не забыть.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">108</b></u><br/><br/>Что море — вот это обидно...",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">109</b></u><br/><br/>Блять, ты понимаешь, что когда люди поймут что это [педофилия] правда...",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">110</b></u><br/><br/>Я вчера такую самсу ахуенную хавал...<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: было сказано сразу после предыдущей цитаты.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">111</b></u><br/><br/>Хочу и думаю.<br/><br/>(прим. редактора: сомнительно.)",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">112</b></u><br/><br/>Глотка девушки — эрогенная зона.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: я кончился. он из меня всю жизнь высосал нахуй когда это сказал.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">113</b></u><br/><br/>Помню такой [псалтырь] на улице нашёл...<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: было сказано с нихуя. ничего этому не предшествовало, и никуда не развилось. живи с этим.)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">114</b></u><br/><br/>— Ты заднеприводный, Большъ?<br/>— Вы нахуя про машины говорите?",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">115</b></u><br/><br/>Если бы меня убили, меня бы сдезь не было.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: ...)</u>",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">116</b></u><br/><br/>— Бидоны или булочки?<br/>— Лучше за водой сходить.",
"<u style=\"color: #75ff75;\"><b style=\"color: #98FB98; font-size: 30px; \">117</b></u><br/><br/>Если бы я жил по зоновским понятиям, я бы пил чифирь и ел сухари.<br/><br/><u style=\"color: #cfe2f3; font-size: 14px;\">(прим. редактора: ой всему своё время, не зарекайся от сумы если биркин, и от тюрьмы если Гиркин.)</u>"],
		// optionally use an HTML element to grab strings from (must wrap each string in a <p>)
		stringsElement: null,
		// typing speed
		typeSpeed: 0.01,
		// time before typing starts
		startDelay: 0,
		// backspacing speed
		backSpeed: 0.01,
		// time before backspacing
		backDelay: 60000,
		// loop
		loop: true,

		shuffle: true,
		// false = infinite
		loopCount: false,
		// show cursor
		showCursor: false,
		// character for cursor
		cursorChar: "|",
		// attribute to type (null == text)
		attr: null,
		// either html or text
		contentType: 'html',
		// call when done callback function
		callback: function() {},
		// starting callback function before each string
		preStringTyped: function() {},
		//callback for every typed string
		onStringTyped: function() {},
		// callback for reset
		resetCallback: function() {}
	});
});
